config/routes.rb
Rails.application.routes.draw do
  get 'posts' => "crawl#crawl", :as => "crawl"
  get 'posts/archive' => "crawl#crawl", :as => "crawl_preview"
  root "application#welcome", :as => "home", via: :all
  post 'blog(/:title)' => "crawl#blog", :as => "blog"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crawl.rb
class Crawl < ApplicationRecord
  def self.crawl_data(tag, next_posts = nil)
    url = "https://medium.com/tag/#{tag}/#{next_posts}"
    unparsed_data = HTTParty.get(url)
    parsed_data = Nokogiri::HTML(unparsed_data)
    posts = parsed_data.css('.streamItem')
    blogs = []
    posts.each do |post|
      author = post.css('.u-accentColor--textDarken').text()
      title = post.css('h3').text()
      details = post.css('time').text() + " " + post.css('span.readingTime').first['title']
      link_title = post.css('a').last['href'].split('.').last
      link = post.css('a').last['href']
      link_title = link_title.index('/') ? link_title[link_title.index('/')+1..link_title.length] : link_title
      img = post.css("img").last['src']
      blogs << {author: author, title: title, details: details, link_title: link_title, link: link, img: img}
    end
    blogs
  end

  def self.blog_data(link)
    data = HTTParty.get(link)
    post = Nokogiri::HTML(data)
    tags_data = (tags_data = post.at_xpath("//script[@type='application/ld+json']")).present? && JSON.parse(tags_data.children.text())['keywords']
    tags = (tags_data.present? && tags_data.map{|tag| tag.include?('Tag') && tag[4..tag.length]}.select{|tag| tag!=false})
    blog_data = post.css('article').css('div').first.css('section').first.inner_html
    {blog_data: blog_data, tags: tags}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def welcome
    render 'layouts/welcome'
  end
end

app/controllers/crawl_controller.rb
class CrawlController < ApplicationController
  def crawl
    @crawl_data = Rails.cache.fetch("#{params['tag']}/#{params['format']}", expires_in: 12.hours) do
      Crawl.crawl_data(params['tag'], params[:format])
    end
  end

  def blog
    time_start = Time.now
    @blog = Rails.cache.fetch("#{params['link']}", expires_in: 12.hours) do
      Crawl.blog_data(params['link'])
    end
    time_end = Time.now
    @blog[:response_time] = time_end - time_start
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crawl_helper.rb
module CrawlHelper
end

app/views/crawl/blog.html.haml
.blog
  = raw @blog[:blog_data]
  - @blog[:tags].each do |tag|
    = form_with(url: crawl_path, method: "get", local: true) do
      = hidden_field_tag 'tag', tag.gsub(" ", '-')
      = submit_tag "##{tag}", :value => "##{tag}"
  %p Response Time: #{@blog[:response_time]} seconds

app/views/crawl/crawl.html.haml
%ul.list-group
- @crawl_data.each do |post|
  %li.list-group-item.post
    .author #{post[:author]}
    .description #{post[:details]}
    .title_blog #{post[:title]}
    = image_tag(post[:img], width: 600, height: 200)
    = form_with(url: blog_path(post[:link_title]), method: "post", local: true) do
      = hidden_field_tag 'link', post[:link]
      = submit_tag "Read Post", :value => "Read Post", :class => "btn btn-info view_post_btn"
  %br
- if @crawl_data.present?
  = form_with(url: crawl_preview_path("archive"), method: "get", local: true) do
    = hidden_field_tag 'tag', params[:tag]
    = submit_tag "Next 10 blogs", :value => "Next 10 blogs", :class => "btn btn-outline-primary next_blogs"
- else
  .alert.alert-warning No blogs found with the given tag

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", :rel => "stylesheet"}/
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"}
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"}
    %title BlogDot
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    .header_home
      .title_resize
        = link_to 'BlogDot', home_path
    = form_with(url: crawl_path, method: "get", local: true) do
      .form-group.input_bx
        %input.input_tag.form-control{:type => "text", :name => "tag", :placeholder => "Enter Tag Name"}
        = submit_tag "view", :value => "Search", :class => 'btn btn-success search'
    %main{:class => "#{controller.controller_name}"}
      = yield